-- Swapnoneer-Ulama-Sangha FINAL-V5
-- নতুন/খালি Supabase Project-এর Database + RLS setup
-- পুরোনো কোনো data এখানে migrate/copy করা হবে না।
--
-- Admin setup:
-- 1) Authentication > Users থেকে Admin user তৈরি করুন।
-- 2) তার UUID কপি করুন।
-- 3) নিচের শেষ INSERT-এর :ADMIN_USER_UUID জায়গায় UUID বসিয়ে চালান।

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  serial_no integer,
  name text not null,
  address text,
  mobile text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  year text not null,
  month integer not null check (month between 1 and 12),
  paid_amount numeric(12,2) not null default 0 check (paid_amount >= 0),
  required_amount numeric(12,2),
  created_at timestamptz not null default now()
);

create table if not exists public.profits (
  id bigint generated by default as identity primary key,
  year text not null,
  description text not null,
  total_profit numeric(12,2) not null default 0 check (total_profit >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  year text not null,
  description text not null,
  amount numeric(12,2) not null default 0 check (amount >= 0),
  date date,
  created_at timestamptz not null default now()
);

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  year text not null,
  date date not null,
  category text not null,
  description text not null,
  amount numeric(12,2) not null default 0 check (amount >= 0),
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  status text not null default 'published',
  publish_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.member_dividend_visibility (
  member_id bigint primary key references public.members(id) on delete cascade,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Indexes needed by FINAL-V5 queries.
create index if not exists payments_member_year_idx on public.payments(member_id, year);
create index if not exists payments_year_month_idx on public.payments(year, month);
create index if not exists members_status_serial_idx on public.members(status, serial_no);
create index if not exists profits_year_idx on public.profits(year);
create index if not exists expenses_year_date_idx on public.expenses(year, date);
create index if not exists assets_status_date_idx on public.assets(status, date);
create index if not exists notices_status_publish_date_idx on public.notices(status, publish_date);

-- Admin check is SECURITY DEFINER so RLS policies do not recursively query admin_users.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- Enable RLS on every application table.
alter table public.members enable row level security;
alter table public.payments enable row level security;
alter table public.profits enable row level security;
alter table public.expenses enable row level security;
alter table public.assets enable row level security;
alter table public.notices enable row level security;
alter table public.admin_users enable row level security;
alter table public.member_dividend_visibility enable row level security;

-- Public read access required by FINAL-V5. Writes remain Admin-only.
drop policy if exists "public can read active members" on public.members;
create policy "public can read active members" on public.members
for select to anon, authenticated using (status = 'active' or public.is_admin());

drop policy if exists "admin can manage members" on public.members;
create policy "admin can manage members" on public.members
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public can read payments" on public.payments;
create policy "public can read payments" on public.payments
for select to anon, authenticated using (true);

drop policy if exists "admin can manage payments" on public.payments;
create policy "admin can manage payments" on public.payments
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public can read profits" on public.profits;
create policy "public can read profits" on public.profits
for select to anon, authenticated using (true);

drop policy if exists "admin can manage profits" on public.profits;
create policy "admin can manage profits" on public.profits
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public can read expenses" on public.expenses;
create policy "public can read expenses" on public.expenses
for select to anon, authenticated using (true);

drop policy if exists "admin can manage expenses" on public.expenses;
create policy "admin can manage expenses" on public.expenses
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public can read active assets" on public.assets;
create policy "public can read active assets" on public.assets
for select to anon, authenticated using (status = 'active' or public.is_admin());

drop policy if exists "admin can manage assets" on public.assets;
create policy "admin can manage assets" on public.assets
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public can read published notices" on public.notices;
create policy "public can read published notices" on public.notices
for select to anon, authenticated using (status = 'published' or public.is_admin());

drop policy if exists "admin can manage notices" on public.notices;
create policy "admin can manage notices" on public.notices
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Admin user table: only an authenticated Admin can read its own/admin rows.
drop policy if exists "admin can read admin users" on public.admin_users;
create policy "admin can read admin users" on public.admin_users
for select to authenticated using (public.is_admin());

drop policy if exists "admin can manage admin users" on public.admin_users;
create policy "admin can manage admin users" on public.admin_users
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Dividend visibility: public can read only Public entries; Admin can manage all.
drop policy if exists "public can read public dividend visibility" on public.member_dividend_visibility;
create policy "public can read public dividend visibility" on public.member_dividend_visibility
for select to anon, authenticated
using (is_public = true or public.is_admin());

drop policy if exists "admin can manage dividend visibility" on public.member_dividend_visibility;
create policy "admin can manage dividend visibility" on public.member_dividend_visibility
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- IMPORTANT: Do NOT run this until the Auth user has been created.
-- Example only:
-- insert into public.admin_users (user_id)
-- values ('PASTE_NEW_AUTH_USER_UUID_HERE');
